### ISSUE TITLE
Add Support for Microsoft Visual Studio 2022 Preview (64-bit)

### ISSUE THREAD

**Issue by ChristophRichner** [triforcely/CollapseLevel#9]
Hi there,

This extension really rocks! I would also like to use it when using VS2022 Preview.

Maybe you can make it happen with a small adjustments?

**Comment by triforcely** [comment]
Hi @ChristophRichner , 2.0.4 version was just published and should work with VS 2022. Let me know if everything is working fine for you.

**Comment by ChristophRichner** [comment]
Works like a charm, you totally rock man!

Thanks, that's awesome 😃
